<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gcn.proto

namespace GCN;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>GCNResult</code>
 */
class GCNResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>map<string, float> node_scores = 1;</code>
     */
    private $node_scores;
    /**
     * Generated from protobuf field <code>string html = 2;</code>
     */
    protected $html = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array|\Google\Protobuf\Internal\MapField $node_scores
     *     @type string $html
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Gcn::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>map<string, float> node_scores = 1;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getNodeScores()
    {
        return $this->node_scores;
    }

    /**
     * Generated from protobuf field <code>map<string, float> node_scores = 1;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setNodeScores($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::FLOAT);
        $this->node_scores = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string html = 2;</code>
     * @return string
     */
    public function getHtml()
    {
        return $this->html;
    }

    /**
     * Generated from protobuf field <code>string html = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setHtml($var)
    {
        GPBUtil::checkString($var, True);
        $this->html = $var;

        return $this;
    }

}

