<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gcn.proto

namespace GCN;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>GCNRequest</code>
 */
class GCNRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.GraphData graph = 1;</code>
     */
    protected $graph = null;
    /**
     * Generated from protobuf field <code>.ModelParams params = 2;</code>
     */
    protected $params = null;
    /**
     * Generated from protobuf field <code>.HistoryData history_data = 3;</code>
     */
    protected $history_data = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \GCN\GraphData $graph
     *     @type \GCN\ModelParams $params
     *     @type \GCN\HistoryData $history_data
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Gcn::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.GraphData graph = 1;</code>
     * @return \GCN\GraphData|null
     */
    public function getGraph()
    {
        return $this->graph;
    }

    public function hasGraph()
    {
        return isset($this->graph);
    }

    public function clearGraph()
    {
        unset($this->graph);
    }

    /**
     * Generated from protobuf field <code>.GraphData graph = 1;</code>
     * @param \GCN\GraphData $var
     * @return $this
     */
    public function setGraph($var)
    {
        GPBUtil::checkMessage($var, \GCN\GraphData::class);
        $this->graph = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ModelParams params = 2;</code>
     * @return \GCN\ModelParams|null
     */
    public function getParams()
    {
        return $this->params;
    }

    public function hasParams()
    {
        return isset($this->params);
    }

    public function clearParams()
    {
        unset($this->params);
    }

    /**
     * Generated from protobuf field <code>.ModelParams params = 2;</code>
     * @param \GCN\ModelParams $var
     * @return $this
     */
    public function setParams($var)
    {
        GPBUtil::checkMessage($var, \GCN\ModelParams::class);
        $this->params = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.HistoryData history_data = 3;</code>
     * @return \GCN\HistoryData|null
     */
    public function getHistoryData()
    {
        return $this->history_data;
    }

    public function hasHistoryData()
    {
        return isset($this->history_data);
    }

    public function clearHistoryData()
    {
        unset($this->history_data);
    }

    /**
     * Generated from protobuf field <code>.HistoryData history_data = 3;</code>
     * @param \GCN\HistoryData $var
     * @return $this
     */
    public function setHistoryData($var)
    {
        GPBUtil::checkMessage($var, \GCN\HistoryData::class);
        $this->history_data = $var;

        return $this;
    }

}

