<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gcn.proto

namespace GCN;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>YearData</code>
 */
class YearData extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 year = 1;</code>
     */
    protected $year = 0;
    /**
     * Generated from protobuf field <code>repeated .PlaceData place_data = 2;</code>
     */
    private $place_data;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $year
     *     @type array<\GCN\PlaceData>|\Google\Protobuf\Internal\RepeatedField $place_data
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Gcn::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 year = 1;</code>
     * @return int
     */
    public function getYear()
    {
        return $this->year;
    }

    /**
     * Generated from protobuf field <code>int32 year = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setYear($var)
    {
        GPBUtil::checkInt32($var);
        $this->year = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .PlaceData place_data = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPlaceData()
    {
        return $this->place_data;
    }

    /**
     * Generated from protobuf field <code>repeated .PlaceData place_data = 2;</code>
     * @param array<\GCN\PlaceData>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPlaceData($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \GCN\PlaceData::class);
        $this->place_data = $arr;

        return $this;
    }

}

