<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gcn.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>GCNResult</code>
 */
class GCNResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>map<string, float> node_scores = 1;</code>
     */
    private $node_scores;
    /**
     * Generated from protobuf field <code>int32 loss = 2;</code>
     */
    protected $loss = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array|\Google\Protobuf\Internal\MapField $node_scores
     *     @type int $loss
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Gcn::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>map<string, float> node_scores = 1;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getNodeScores()
    {
        return $this->node_scores;
    }

    /**
     * Generated from protobuf field <code>map<string, float> node_scores = 1;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setNodeScores($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::FLOAT);
        $this->node_scores = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 loss = 2;</code>
     * @return int
     */
    public function getLoss()
    {
        return $this->loss;
    }

    /**
     * Generated from protobuf field <code>int32 loss = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setLoss($var)
    {
        GPBUtil::checkInt32($var);
        $this->loss = $var;

        return $this;
    }

}

