<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gcn.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>GraphData</code>
 */
class GraphData extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .Node nodes = 1;</code>
     */
    private $nodes;
    /**
     * Generated from protobuf field <code>repeated .Edge edges = 2;</code>
     */
    private $edges;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Node>|\Google\Protobuf\Internal\RepeatedField $nodes
     *     @type array<\Edge>|\Google\Protobuf\Internal\RepeatedField $edges
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Gcn::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .Node nodes = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getNodes()
    {
        return $this->nodes;
    }

    /**
     * Generated from protobuf field <code>repeated .Node nodes = 1;</code>
     * @param array<\Node>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setNodes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Node::class);
        $this->nodes = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Edge edges = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getEdges()
    {
        return $this->edges;
    }

    /**
     * Generated from protobuf field <code>repeated .Edge edges = 2;</code>
     * @param array<\Edge>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setEdges($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Edge::class);
        $this->edges = $arr;

        return $this;
    }

}

