<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gcn.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>HistoryData</code>
 */
class HistoryData extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .YearData year_data = 1;</code>
     */
    private $year_data;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\YearData>|\Google\Protobuf\Internal\RepeatedField $year_data
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Gcn::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .YearData year_data = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getYearData()
    {
        return $this->year_data;
    }

    /**
     * Generated from protobuf field <code>repeated .YearData year_data = 1;</code>
     * @param array<\YearData>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setYearData($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \YearData::class);
        $this->year_data = $arr;

        return $this;
    }

}

