<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gcn.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>PlaceData</code>
 */
class PlaceData extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string place = 1;</code>
     */
    protected $place = '';
    /**
     * Generated from protobuf field <code>double longitude = 2;</code>
     */
    protected $longitude = 0.0;
    /**
     * Generated from protobuf field <code>double latitude = 3;</code>
     */
    protected $latitude = 0.0;
    /**
     * Generated from protobuf field <code>int32 total_people = 4;</code>
     */
    protected $total_people = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $place
     *     @type float $longitude
     *     @type float $latitude
     *     @type int $total_people
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Gcn::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string place = 1;</code>
     * @return string
     */
    public function getPlace()
    {
        return $this->place;
    }

    /**
     * Generated from protobuf field <code>string place = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPlace($var)
    {
        GPBUtil::checkString($var, True);
        $this->place = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double longitude = 2;</code>
     * @return float
     */
    public function getLongitude()
    {
        return $this->longitude;
    }

    /**
     * Generated from protobuf field <code>double longitude = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setLongitude($var)
    {
        GPBUtil::checkDouble($var);
        $this->longitude = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double latitude = 3;</code>
     * @return float
     */
    public function getLatitude()
    {
        return $this->latitude;
    }

    /**
     * Generated from protobuf field <code>double latitude = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setLatitude($var)
    {
        GPBUtil::checkDouble($var);
        $this->latitude = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 total_people = 4;</code>
     * @return int
     */
    public function getTotalPeople()
    {
        return $this->total_people;
    }

    /**
     * Generated from protobuf field <code>int32 total_people = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setTotalPeople($var)
    {
        GPBUtil::checkInt32($var);
        $this->total_people = $var;

        return $this;
    }

}

